### ISSUE TITLE
Error when sending ipfs file to unregistered address

### ISSUE THREAD

**Issue by AegeusCoin** [AegeusCoin/aegeus-ui#44]
When attempting to send a file to an unregistered address, an exception is thrown.  This behavior should be changed to gracefully inform the user that the recipient's key could not be located.

**Comment by linusx** [comment]
This is Java code and not UI code.

**Comment by AegeusCoin** [comment]
This currently produces a warning without throwing an exception such as this one:

Cannot obtain encryption key for: [addr=AcRfAGsmVBGDSETz8VdVJmQzt9mXA38TbW, ro=true, labels=[unregistered]]! 

Closing this issue in light of that.
